server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway

 #http://127.0.0.1:9527/microservicecloud-dept/dept/get/1
eureka: 
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: 127.0.0.1:9527
    prefer-ip-address: true 
 

 #http://127.0.0.1:9527/jsjchai/mydept/dept/get/1
zuul:
  prefix: /jsjchai
   #ignored-services: microservicecloud-dept  #单个微服务
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
#
info:
  app.name: zuul-microcloud
  company.name: 127.0.0.1
  build.artifactId: $project.artifactId$
  build.version: $project.version$

